### PR TITLE
feat(instance): adding IMDSv2 support on instance

### PR DESCRIPTION
**Pull request by titouan-joseph**
For security reason, adding possibility to enable IMDSv2

### CODE REVIEW

**Comment by titouan-joseph** [comment]
@RavinderReddyF5 can watch this MR. Thank you

**Comment by titouan-joseph** [comment]
@RavinderReddyF5 @urohit011
Can you have a look on this PR please? 
We are waiting for this to deploy our F5 bigip instances

**Comment by RavinderReddyF5** [comment]
Hi @titouan-joseph, thanks for your PR, sure will check on this can you please submit CLA.

**Comment by titouan-joseph** [comment]
> Hi @titouan-joseph, thanks for your PR, sure will check on this can you please submit CLA.

Yes sur, will check to do the submit asap

**Comment by titouan-joseph** [comment]
Hello @RavinderReddyF5,

Just send the CLA by mail

**Pull request merged**
